name = "LevelSetMethods"

[deps]
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProfileVega = "4391764f-db79-4bd7-a4c6-f9062de4300e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DrWatson = "2.12.0"
julia = "1.7.2"
